export const USER_PREFILLS = {
  'gatama bashir': {
    formData: {
      user_name: 'GATAMA BASHIR',
      invoice_date: '2025-10-24',
      ship_name: 'Not yet',
      ship_date: '',
      port_of_loading: 'Yokohama',
      port_of_discharge: 'Dar Es Salaam',
      departure_port: 'Yokohama',
      arrival_port: 'Dar Es Salaam',
      destination: 'Rwanda',
      address: 'RUBAVU DISTRICT',
      phone: '+250787013075',
      company: 'Gatama Bashir',
      door: '4',
      seat: '5',
    },
    freight: '0',
    discount: '0',
  },
};

export const DEFAULT_FORM_DATA = {
  refNo: '',
  make: '',
  model: '',
  price: '',
  category: '',
  color: '',
  year: '',
  invoice_date: '',
  dimension: '',
  m3: '',
  engineCapacity: '',
  mileage: '',
  chassisNo: '',
  fuel: '',
  door: '',
  seat: '',
  transmission: '',
  drive: '',
  stereo: '',
  port_of_discharge: '',
  port_of_loading: '',
  engine_type: '',
  destination: '',
  departure_port: '',
  user_name: '',
  address: '',
  phone: '',
  company: '',
  size: '',
  ship_name: '',
  ship_date: '',
  arrival_port: '',
};

export const DEFAULT_COSTS = {
  buyingPrice: '',
  auctionFee: '',
  transportation: '',
  yardFee: '',
  photosFee: '',
  othersFee: '',
  serviceFee: '',
};

export const SAMPLE_FORM_DATA = {
  refNo: 'ELJ-1003',
  make: 'Volkswagen',
  model: 'Golf',
  price: '',
  category: 'Hatchback',
  color: 'Black',
  year: '2023',
  invoice_date: '2024-06-01',
  dimension: '429 x 179 x 147 (cm)',
  m3: '11.288 m3',
  engineCapacity: '2,000cc',
  mileage: 'odo 7,236km',
  chassisNo: 'WVWZZZCD4RW011433',
  fuel: 'Diesel',
  door: '5',
  seat: '5',
  transmission: 'Automatic',
  drive: '2WD',
  stereo: 'Standard',
  ship_date: '2024-06-01',
  ship_name: 'MV Ocianic',
  arrival_port: 'Los Angeles',
  size: 'test size',
  port_of_discharge: 'Los Angeles',
  port_of_loading: 'Tokyo',
  engine_type: 'Petrol',
  destination: '123 Elm St, Springfield',
  departure_port: 'Tokyo Port',
  user_name: 'Sample Customer',
  address: '123 Elm St, Springfield',
  phone: '123-456-7890',
  company: 'Doe Enterprises',
};

export const SAMPLE_COSTS = {
  buyingPrice: '1000000',
  auctionFee: '50000',
  transportation: '30000',
  yardFee: '10000',
  photosFee: '5000',
  othersFee: '2000',
  serviceFee: '100000',
};

export const CURRENCIES = ['JPY', 'USD', 'EUR'];
